In [49]:
import os
import csv
import pandas as pd

In [50]:
restaurant_df = pd.read_csv('raw.csv')

In [51]:
restaurant_df.head()

,restaurant,address,city,state,country,latitude,longitude,tel,website,price,rating
0,Chipotle Mexican Grill,126 New,San Francisco,'region': 'CA',US,'latitude': 37.787086,'longitude': -122.400212,'tel': '(415) 512-8113',website':,'price': '1','rating': 3.0
1,In-N-Out Burger,333 Jefferson St,San Francisco,'region': 'CA',US,'latitude': 37.8078,'longitude': -122.418383,'tel': '(800) 786-1000',website','price': '3','rating': 4.0
2,Pearls Deluxe Burgers,708 Post St,San Francisco,'region': 'CA',US,'latitude': 37.787739,'longitude': -122.413641,'tel': '(415) 409-6120','email':,'price': '3','rating': 4.0
3,Cafe Du Soleil,200 Fillmore St,San Francisco,'region': 'CA',US,'latitude': 37.771303,'longitude': -122.430158,'tel': '(415) 934-8637','email':,'price': '3','rating': 4.5
4,Cafe Zazo,64 14th St,San Francisco,'region': 'CA',US,'latitude': 37.768642,'longitude': -122.414821,'tel': '(415) 626-5555','email':,'price': '1','rating': 4.0

In [ ]:
restaurant_dfdata['result'] = data['result'].map(lambda x: x.lstrip('+-').rstrip('aAbBcC'))